### ISSUE TITLE
Internationalization Issue on Dashboard 

### ISSUE THREAD

**Issue by bathini79** [napse-invest/Napse#18]
When User switched to english , The introductury copy is not in english,which is not consistent , Would Like To Fix It. But I Couln't Find Its respective repo here!Can you confirm if that's true? Thanks!
![image](https://github.com/napse-invest/Napse/assets/116077457/2fa31d44-f4b0-4350-8af4-58821333e40b)

**Comment by tomjeannesson** [comment]
Hi! Thanks for reporting this bug! 

We are currently migrating from closed to open source. The website is still closed source for the moment. This repo will be where the desktop app will be developed (should start construction this week).

I'll get the issue fixed in our closed-source repo.

If you have any questions, feel free to ask!

**Comment by tomjeannesson** [comment]
@Cereal38 could you please fix this?

**Comment by bathini79** [comment]
Thanks for the info!

**Comment by Cereal38** [comment]
Fix will be in production tomorrow
